name: "✨ Feature Request"
description: "Suggest an idea for this project "
title: "Feat:Add suitable title here"
labels: [Enhancement]
body:
  - type: textarea
    attributes:
      label: "Describe the feature"
      description:
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Add ScreenShots"
      description: "Add sufficient SS to explain your issue."
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: "Record"
      options:
        - label: "I agree to follow this project's Code of Conduct"
          required: true
        - label: I have checked the existing [issues](https://github.com/Data-Sculptor-X/VOJ-ReactJS/issues)
          required: true
        - label: "I'm a GSSOC'24-Extended contributor"
        - label: "I want to work on this issue"